### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by skerbis** [KLXM/uikit_news#1]
- [ ] TableSet für News
- [ ] Module
- [ ] URL Definitionen
- [ ] Fragmente

**Comment by AWqxKAWERbXo** [comment]
@skerbis wenn du möchtest, lass uns dazu (telefonisch) austauschen - mach's doch losgelöst von uikit und liefere nur passende uikit-Fragmente, dann könntest du direkt hier miteinsteigen. https://github.com/alexplusde/neues

**Comment by skerbis** [comment]
oops ... sollte eigentlich ein geheimes Addon werden. Nicht für die Öffentlichkeit. Dennoch danke für dein Angebot.
